# palette = "catppuccin_latte"
palette = "catppuccin_mocha"
add_newline = true
format = """
$azure\
$gcloud\
$kubernetes\
${custom.git}\
$container\
${custom.host}\
$python\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character
"""

[azure]
symbol = '󰠅  '
format = '''
[$symbol$subscription \(($username)\)]($style)
'''
style = 'dimmed bold green'
disabled = true

[character]
success_symbol = '[](bold green) '
error_symbol = '[](bold red) '

[container]
symbol = ' '
format = '[$symbol]($style) '
style = 'bold green'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold green'

[gcloud]
symbol = '󱇶 ' 
format = '''
[$symbol $project \($account(@$domain)(\($region\))\)]($style) 
'''
style = 'dimmed bold green'
disabled = true

[git_branch]
symbol = ''
format = '[on $symbol$branch(:$remote_branch)]($style) '
style = 'bold purple'

[git_commit]
format = '[$hash$tag]($style) '
commit_hash_length = 6
only_detached = false
tag_disabled = false
disabled = false
style = 'bold purple'

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '
style = 'bold purple'

[helm]
format = '[$symbol]($style) '
detect_extensions = []
detect_folders = ['helm']
disabled = false

[kubernetes]
symbol = '󱃾  '
format = '''
[$symbol$context (\($namespace\))]($style)
'''
style = 'dimmed bold green'
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'bold purple'

[custom.docker]
command = ''
symbol = '󰡨'
style = 'yellow bold'
detect_files = ['Dockerfile']
format = '[$symbol]($style) '

[custom.folder]
when  = 'ls -d */'
symbol = ''
style = 'yellow bold'
format = '[$symbol]($style) '

[custom.git]
command = 'git config --get remote.origin.url'
when = true
require_repo = true
symbol = ''
format = '''
[$symbol  ($output)]($style) 
'''
style = 'dimmed bold green'

[custom.host]
symbol = ''
when = 'if test -f /.dockerenv; return 1; end'
format = '[$symbol]($style)  '
style = 'bold green'

[custom.json]
command = ''
symbol = ''
style = 'yellow bold'
detect_extensions = ['json']
format = '[$symbol]($style) '

[custom.python]
command = ''
symbol = ''
style = 'yellow bold'
detect_files = ['requirements.txt']
detect_extensions = ['py','ipynb']
format = '[$symbol]($style) '

[custom.shell]
command = ''
symbol = ''
style = 'yellow bold'
detect_extensions = ['sh']
format = '[$symbol]($style) '

[custom.text]
command = ''
symbol = '󰦨'
style = 'yellow bold'
detect_extensions = ['txt']
format = '[$symbol]($style) '

[custom.toml]
command = ''
symbol = ''
style = 'yellow bold'
detect_extensions = ['toml']
format = '[$symbol]($style) '

[custom.yaml]
command = ''
symbol = ''
style = 'yellow bold'
detect_extensions = ['yml','yaml']
format = '[$symbol]($style) '

[os.symbols]
Android = ""
Arch = "󰣇"
Debian = "󰣚"
Fedora = ""
Macos = ""
NixOS = "󱄅"
Pop = " "
Raspbian = ""
Ubuntu = "󰕈"
Unknown = " "
Windows = "󰖳"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
